export default {
    routes:[
        {
            path:"/",
            name:"Home",
            component:()=>import("../views/Home"),
        },
        {
            path:"/login",
            name:"Login",
            component:()=>import("../views/Login"),
        },
        {
            path:"/register",
            name:"Register",
            component:()=>import("../views/Register"),
        },
        {
            path:"/channel/:id",
            name:"ChannelNews",
            component:()=>import("../views/ChannelNews"),
        },
        {
            path:"*",
            name:"404",
            component:()=>import("../views/NotFound"),
        },
    ],
    mode:"history"

}